apiVersion: v1
kind: Service
metadata:
  name: esioci-ui
  labels:
    app: esioci
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: esioci
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esioci-ui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: esioci
        tier: frontend
    spec:
      containers:
      - name: esioci-ui
        image: gcr.io/esio-test/esioci-ui:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
