apiVersion: v1
kind: Service
metadata:
  name: esioci
  labels:
    app: esioci
    tier: backend
spec:
  ports:
  - port: 4000
  selector:
    app: esioci
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esioci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esioci
        tier: backend
    spec:
      containers:
      - name: esioci
        image: gcr.io/esio-test/esioci:11
        resources:
          requests:
            cpu: 300m
            memory: 1000Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ESIOCI_DB_HOST
          value: postgresql
        - name: ESIOCI_REDIS
          value: redis://redis:6379
        ports:
        - containerPort: 4000
