apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: esioci
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 4000
  selector:
    app: esioci
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esioci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esioci
        tier: frontend
    spec:
      containers:
      - name: esioci-api
        image: gcr.io/esio-test/esioci:3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ESIOCI_DB_HOST
          value: postgresql
        ports:
        - containerPort: 4000
