apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: psql
        tier: backend
    spec:
      containers:
      - name: master
        image: postgres:9.6.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: psql
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: psql
    tier: backend
